import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const chirpBold = localFont({
  src: './_ui/fonts/Chirp-Bold.ttf',
  variable: '--font-chirp-bold',
  display: 'swap',
})
const chirpRegular = localFont({
  src: './_ui/fonts/Chirp-Regular.ttf',
  variable: '--font-chirp-regular',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${chirpBold.variable} ${chirpRegular.variable}`}>
        {children}
      </body>
    </html>
  )
}
